---

  - name: Download Java
    get_url:
      url={{download_url}}
      dest={{download_folder}}
      headers='Cookie:oraclelicense=accept-securebackup-cookie'

  - name: Unpack rpm
    yum:
       name: "{{java_archive}}"
       state: present

  - name: Fix ownership
    file: state=directory path={{java_name}} owner=root group=root recurse=yes

  - name: Make Java available for system
    command: 'alternatives --install "/usr/bin/java" "java" "{{java_name}}/bin/java" 2000'

  - name: Clean up
    file: state=absent path={{java_archive}}
