---

- name: Installing PreRequisites
  hosts: all
  roles: 
    - PreRequisite

- name: Downloading Ambari Repo
  hosts: all
  roles:
    - AmbariRepo

- name: Setup Ambari Server
  hosts: ambari
  roles:
    - AmbariServer

- name: Setup Ambari Agent
  hosts: all
  roles:
    - AmbariAgent

- name: Apply Blueprint
  hosts: ambari
  roles: 
    - blueprint
