---
- hosts: all
  vars:
    download_url: http://download.oracle.com/otn-pub/java/jce/8/jce_policy-8.zip
    download_folder: /opt
    unpack_folder: /usr/java/latest/jre/lib/security/

  tasks:
  - name: Download JCEPolicy
    get_url:
      url={{download_url}}
      dest={{download_folder}}
      headers='Cookie:oraclelicense=accept-securebackup-cookie'
  
  - unarchive: src={{download_folder}}/jce_policy-8.zip dest={{unpack_folder}} copy=no

